import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Sidebar from '../Components/Sidebar';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Amazon WEB 3.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      {/* <Main /> */}
    </div>
  )
}
