import Head from 'next/head';
import styles from '../styles/Home.module.css';
import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
import Navbar from '../Components/Navbar';
import ProductsContainer from '../Components/ProductsContainer';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Amazon WEB 3.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <ProductsContainer />
    </div>
  )
}
