import Head from 'next/head';
import '../styles/globals.css';
import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
import 'react-toastify/dist/ReactToastify.css';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Amazon Web 3.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href='https://blog.logomyway.com/wp-content/uploads/2021/11/Ethereum-logo.png' />
      </Head>
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
